from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from src.models.session import Session


class BaseSessionManager(Protocol):
    async def create_session(self, session_id: str) -> Session: ...

    async def get_session(self, session_id: str) -> Session | None: ...

    async def get_or_create_session(self, session_id: str) -> Session: ...

    async def update_session(self, session: Session) -> None: ...

    async def delete_session(self, session_id: str) -> None: ...

    async def add_user_transcript(self, session_id: str, text: str) -> None: ...

    async def add_agent_transcript(self, session_id: str, text: str) -> None: ...

    async def get_transcript_text(self, session_id: str) -> str: ...

    async def list_sessions(self) -> list[str]: ...

    async def get_active_count(self) -> int: ...
